apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mini-argocd-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mini-argocd-controller
subjects:
  - kind: ServiceAccount
    name: mini-argocd-controller
    namespace: mini-argocd
